2023-01-03 18:47:28,401 ERROR: Exception on /index [GET] [in C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\routes.py", line 21, in index
    posts = current_user.followed_posts.all()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'all'
2023-01-03 18:47:30,723 ERROR: Exception on /index [GET] [in C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\routes.py", line 21, in index
    posts = current_user.followed_posts.all()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'all'
2023-01-03 18:48:22,285 INFO: Microblog startup [in C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\__init__.py:48]
2023-01-03 18:48:29,002 ERROR: Exception on /user/john [GET] [in C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\routes.py", line 71, in user
    return render_template('user.html', user=user, posts=posts, form=form)
                                                                     ^^^^
NameError: name 'form' is not defined
2023-01-03 18:49:18,168 INFO: Microblog startup [in C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\__init__.py:48]
2023-01-03 18:50:10,868 INFO: Microblog startup [in C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\__init__.py:48]
2023-01-03 18:52:50,056 INFO: Microblog startup [in C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\__init__.py:48]
2023-01-03 18:52:53,069 ERROR: Exception on /index [GET] [in C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\routes.py", line 22, in index
    return render_template('index.html', title='Home', posts=posts, form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\templates\base.html", line 32, in top-level template code
    {% block content%} {% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\templates\index.html", line 21, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\templates\_post.html", line 4, in top-level template code
    <img src="{{ user.avatar(32) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FaheemNoorani\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user' is undefined
2023-01-03 18:53:13,624 INFO: Microblog startup [in C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\__init__.py:48]
2023-01-05 19:27:15,292 INFO: Microblog startup [in C:\Users\FaheemNoorani\PycharmProjects\GiftExchange\app\__init__.py:48]
